 const languages = [
    "Afrikaans",
    "Arabic",
    "Azerbaijani",
    "Bashkir",
    "Belarusian",
    "Bulgarian",
    "Bengali",
    "Bosnian",
    "Catalan",
    "Montenegrin",
    "Czech",
    "Chuvash",
    "Welsh",
    "Danish",
    "German",
    "Greek",
    "English",
    "Esperanto",
    "Spanish",
    "Estonian",
    "Basque",
    "Persian",
    "Finnish",
    "French",
    "French (Canada)",
    "Irish",
    "Gujarati",
    "Hebrew",
    "Hindi",
    "Croatian",
    "Haitian",
    "Hungarian",
    "Armenian",
    "Indonesian",
    "Icelandic",
    "Italian",
    "Japanese",
    "Georgian",
    "Kazakh",
    "Central Khmer",
    "Korean",
    "Kurdish",
    "Kirghiz",
    "Lao",
    "Lithuanian",
    "Latvian",
    "Malayalam",
    "Mongolian",
    "Marathi",
    "Malay",
    "Maltese",
    "Burmese",
    "Norwegian Bokmal",
    "Nepali",
    "Dutch",
    "Norwegian Nynorsk",
    "Punjabi",
    "Punjabi (Shahmukhi script, Pakistan)",
    "Polish",
    "Pushto",
    "Portuguese",
    "Romanian",
    "Russian",
    "Sinhala",
    "Slovakian",
    "Slovenian",
    "Somali",
    "Albanian",
    "Serbian",
    "Swedish",
    "Tamil",
    "Telugu",
    "Thai",
    "Tagalog",
    "Turkish",
    "Ukrainian",
    "Urdu",
    "Vietnamese",
    "Simplified Chinese",
    "Traditional Chinese"
  ]
   
export default languages;